config/routes.rb
Microblog::Application.routes.draw do
  devise_for :admins

  namespace :admin do
    resources :posts do
      resources :comments
    end
    resources :categories

    root :to => 'categories#index'
  end

  resources :posts, only: [:index, :show] do
    resources :comments, only: [:show, :create]
  end

  resources :categories, only: [:index, :show]

  root :to => 'posts#index'

  

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :category
  has_many :comments, dependent: :destroy

  validates_presence_of :title, :content, :category_id
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < AdminController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comments = @post.comments
    @comment = @post.comments.build
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      begin
        PostCreateService.new.process @post
        format.html { redirect_to admin_post_path(@post), notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }

      rescue PostCreateService::PostCreateError
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to admin_post_path(@post), notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to admin_posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :category_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comments = @post.comments
    @comment = @post.comments.build
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_path(@post), notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end

  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :category_id)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/posts/_form.html.erb
<%= form_for([:admin, @post]) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br />
    <%= f.select(:category_id, Category.all.map {|category| [category.name, category.id]}, include_blank: true ) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/posts/_posts.erb
<%= link_to 'New Post', new_admin_post_path %><br />
<% @posts.each do |post| %>
    <div class="post">
      <h2><%= link_to post.title, admin_post_path(post) %></h2>
      Kategoria: <%= link_to post.category.name, admin_category_path(post.category) %><br />
      <%= link_to 'Show', admin_post_path(post) %>
      <%= link_to 'Edit', edit_admin_post_path(post) %>
      <%= link_to 'Destroy', admin_post_path(post), method: :delete, data: { confirm: 'Are you sure?' } %><br />
      <p><%= post.content %></p>
    </div>
<% end %>

app/views/admin/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', admin_posts_path %>

app/views/admin/posts/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Wszystkie posty</h1>
<%= render :partial => 'posts' %>

app/views/admin/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_posts_path %>

app/views/admin/posts/show.html.erb
<h2><%= @post.title %></h2>
<%= link_to @post.category.name, admin_category_path(@post.category) %><br />
<%= link_to 'Edit', edit_admin_post_path(@post) %> |
<%= link_to 'Destroy', admin_post_path(@post), method: :delete, data: { confirm: 'Are you sure?' } %><br />


<p>
  <%= @post.content %>
</p>

<p id="notice"><%= notice %></p>

<%= render 'admin/comments/form' %>

<!--using range to make sure new empty comment is not displayed-->
<% @comments[0..-2].each do |comment| %>
    <%= "#{comment.nick} napisal:" %><br />
    <%= comment.content %><br />
    <%= link_to 'Delete', admin_post_comment_path(@post, comment), method: :delete, confirm: 'Are you sure?' %><br /><br />
<% end %>