config/routes.rb
Microblog::Application.routes.draw do
  devise_for :admins

  namespace :admin do
    resources :posts do
      resources :comments
    end
    resources :categories

    root :to => 'categories#index'
  end

  resources :posts, only: [:index, :show] do
    resources :comments, only: [:show, :create]
  end

  resources :categories, only: [:index, :show]

  root :to => 'posts#index'

  

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Microblog</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="top">
  <h1>Super microblog!</h1>
</div>

<div id="categories">
  <%= current_admin.email %>
  <%= link_to 'Logout', destroy_admin_session_path, method: :delete, class: 'admin'  %>
  <h2>Categories</h2>
  <% @all_categories.each do |category| %>
      <%= link_to category.name, admin_category_path(category) %><br />
  <% end %>
  <br />

  <%= link_to 'Wszystkie posty', admin_posts_path %><br />
  <%= link_to 'All categories', admin_categories_path %><br /><br />
  <%= link_to 'Add category', new_admin_category_path %>
</div>

<div id="main_content">
  <%= yield %>
</div>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Microblog</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="top">
  <h1>Super microblog!</h1>
</div>

<div id="categories">
  <h2>Categories</h2>
  <% @all_categories.each do |category| %>
    <%= link_to category.name, category_path(category) %><br />
  <% end %>
  <br />

  <%= link_to 'Wszystkie posty', root_path %><br /><br />
  <%= link_to 'Add category', new_category_path %>
</div>

<div id="main_content">
  <%= yield %>
</div>

</body>
</html>